name: 'Social media integrations'

on:
  push:
    branches: ['master', 'develop']
jobs:
  CreateImage:
    name: Create repo img for social media
    runs-on: ubuntu-latest
    steps:
      - name: Open Graph social cards
        uses: Jasmin2895/open-graph-image@v1.1
        with:
          bold-text: 'RodCordeiro API'
          plain-text: 'for personal assistance and project managements'
          theme: 'dark'
      - name: List files
        run: |
          ls
      - name: Send image to discord channel
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: og-image.now.sh.png
      - name: Archive open graph image
        uses: actions/upload-artifact@v2
        with:
          name: open-graph-image
          path: og-image.now.sh.png

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
  Resk:
    name: Create code gists for example
    runs-on: ubuntu-latest
    steps:
      - name: Resk
        uses: maticzav/resk@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
